repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.5  # Use the latest stable version
    hooks:
      - id: ruff
        args: ["--fix", "--exit-zero"]
      - id: ruff-format
      
  - repo: local
    hooks:
      - id: re-add
        name: Re-add files modified by hooks
        entry: bash -c 'git add -u'
        language: system
        stages: [pre-commit, post-commit]
        always_run: true
        pass_filenames: false
