repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.5  # Use the latest stable version
    hooks:
      - id: ruff
        args: ["check", "--select", "I", "--fix"]
      - id: ruff-format  

