repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.212  # Use the latest stable version
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: local
    hooks:
      - id: re-add
        name: Re-add files modified by hooks
        entry: bash -c 'git add -u'
        language: system
        always_run: true
        pass_filenames: false
