name: Code Quality

on: 
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'  # Ensure the appropriate Python version is used
      - name: Install dependencies
        run: |
          pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files


  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: mypy POC --check-untyped-defs --ignore-missing-imports
           # NOTE: this needs to be the same as the job name