name: Code Quality

on: 
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Ensure the appropriate Python version is used
      - name: Install dependencies
        run: |
          pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
